### ISSUE TITLE
SWITCH TO GIT HUB PAGES SO THAT WE CAN VIEW THE WORKING OF THE PAGE ON GIT HUB

### ISSUE THREAD

**Issue by MAVERICK-VF142** [vermakamya/Donate_food_Hacktoberfest-2022#15]
GO TO YOUR REPOSITORY SETTINGS AND THEN TO PAGES AND THEN PUBLISH IT
 

so it will look like this @vermakamya 
https://maverick-vf142.github.io/Donate_food_Hacktoberfest-2022/

**Comment by vermakamya** [comment]
Good work!
Happy Hacking.
