### ISSUE TITLE
Add a form for volunteer sign up

### ISSUE THREAD

**Issue by vermakamya** [vermakamya/Donate_food_Hacktoberfest-2022#3]
Contains unique id, password, organisation name etc.

**Comment by ProtyayMnd50** [comment]
Can you assign me this @vermakamya ?

**Comment by MAVERICK-VF142** [comment]
assign it to me

**Comment by MAVERICK-VF142** [comment]
already uploaded the pull request

**Comment by MAVERICK-VF142** [comment]
@vermakamya the work is done you can close the issue
