### ISSUE TITLE
I want to add a scroll to top button.

### ISSUE THREAD

**Issue by yashlondhe90960** [vermakamya/Donate_food_Hacktoberfest-2022#43]
Adding scroll to top button, please assign this to me.

**Comment by vermakamya** [comment]
Sure, go ahead.

**Comment by yashlondhe90960** [comment]
Please merge #45 Its made by me

**Comment by yashlondhe90960** [comment]
Hey, I've added the scroll to top button. Kindly look into it.

**Comment by vermakamya** [comment]
sure, Thanks.

**Comment by yashlondhe90960** [comment]
Thank you so much......Shall I close this issue?

**Comment by vermakamya** [comment]
yeah, you can close this issue, go ahead.
HAPPY HACKING
