### ISSUE TITLE
image issue

### ISSUE THREAD

**Issue by MAVERICK-VF142** [vermakamya/Donate_food_Hacktoberfest-2022#71]
sign in image is of low resolution and there is no image in forget password page and sign up page

@sarthak027 -- fix it

**Comment by MAVERICK-VF142** [comment]
- [ ] change the low resolution image in sign in page
- [ ] add image to forget password page
- [ ] add image to sign up page

**Comment by Sarthak027** [comment]
Please assign it to me

**Comment by vermakamya** [comment]
@Sarthak027 go ahead.
HAPPY HACKING

**Comment by Sarthak027** [comment]
I have fixed the problem and pushed it.
